# Generated by Django 4.0.4 on 2022-06-04 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='commAutor',
            new_name='commAuthor',
        ),
    ]
