# Generated by Django 4.0.4 on 2022-06-30 17:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('news', '0004_alter_subscribersmail_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscribersmail',
            name='category',
            field=models.TextField(default='category_none'),
        ),
        migrations.AddField(
            model_name='subscribersmail',
            name='subscriber',
            field=models.TextField(default='subscriber_none'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='commAuthor',
            field=models.ForeignKey(default='Guest ', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
