# Generated by Django 4.0.4 on 2022-07-11 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_subscribersmail_category_subscribersmail_subscriber_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscribersmail',
            name='subscriber_email',
            field=models.TextField(default='support@gmail.com'),
        ),
    ]
