# Generated by Django 4.0.5 on 2022-06-25 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_subscategory_alter_category_subscribers_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscategory',
            old_name='user',
            new_name='subscribers',
        ),
    ]
